### ISSUE TITLE
Integrating with ember-cli

### ISSUE THREAD

**Issue by venusang** [kalcifer/ember-dragula#1]
Is this supposed to work with ember-cli? Or are there additional instructions that are not included here?  I've been wracking my brain trying to get this work with my ember-cli project and so far I have a headache :(  I'm new to ember-cli and addons so it could very well be that I am misunderstanding the instructions.

**Comment by pksjce** [comment]
Hey,
In your ember-cli project, just say 

<pre>ember install ember-dragula</pre>

Once the addon is installed, You can can use the syntax given in the READMe to make draggable elements and droppable containers. Checkout https://github.com/kalcifer/ember-dragula/tree/master/tests/dummy/app for its full usage.

**Comment by venusang** [comment]
Okay let me check out the sample repo you sent over because I did those things (several times) and it did not work for me :(  _crossing fingers_

Thank you!

**Comment by venusang** [comment]
Ok, now I see what the issue was for me and I actually suspected this was the disconnect!  It was not clear to me where and how to define the dragulaoptions.  I see you have them in the app/routes/application.js file.  I'll give this a shot and hopefully it will work for me.  Thanks again!

**Comment by venusang** [comment]
Hi again..... 

So, I was getting this error before and after I updated my code to reflect what you have in your test app (screenshot attached).  But just in case the screenshot is hard to read, the error says "Cannot read property 'options' of undefined" and it references ember-dragula.js:7

![screenshot 2015-08-14 10 13 52](https://cloud.githubusercontent.com/assets/7906064/9279567/41441cb8-426d-11e5-8c77-9fbb87e95176.png)

I copied and pasted the helper template code shown in your test app into my application.hbs file.  I also copy and pasted the code in your app/routes/application.js into my app/routes/application.js.  I even placed a copy of the tree-helper.js in my app/components/ directory.

Not sure what it is that I am missing.

**Comment by pksjce** [comment]
Hey! Sorry you are having trouble integrating this.

So the config parameter requires an object of following contract

<pre>
{
    'options':{
        //all dragula options
    },
    'eventList':[{
        name:'drag'
    },{
        name:'drop'
    }] // all the events you want to listen to. Pick it from the dragula homepage.
}
</pre>

The `options` and `eventList` are required params in the config object

**Comment by pksjce** [comment]
Hi,
I will close this issue for now. Please reopen at your discretion.
