### ISSUE TITLE
bower dependency not included

### ISSUE THREAD

**Issue by sly7-7** [kalcifer/ember-dragula#11]
Using ember cli 2.3.0.beta2, `ember install ember-dragula` does not include the dragula library in the bower_components library. I have to manually `bower install --save dragula` to make it work.

Is that usual, or should the addon do the necessary thing to update my app's bower.json and install dragula by its own ?

**Comment by pksjce** [comment]
I guess it requires a postinstall script. Would really appreciate a PR. If not I will get to it by this week.

**Comment by sly7-7** [comment]
I will gladly look into this. For now, I can't see a difference between yours and for example this addon: https://github.com/yapplabs/ember-tether which includes tether. During the installation, ember-cli is printing 

```
Installed packages for tooling via npm.
installing ember-tether
  install bower package tether
Installing browser packages via Bower...
  cached git://github.com/HubSpot/tether.git#1.1.1
Installed browser packages via Bower.
Installed addon package.
```

**Comment by sly7-7** [comment]
Good news, I found it: http://ember-cli.com/extending/#default-blueprint

So I will try to resolve this creating this blueprint and importing the bower dependency.
