### ISSUE TITLE
Publish the latest to npm

### ISSUE THREAD

**Issue by ro0gr** [kalcifer/ember-dragula#33]
Hi! It's a great addon, thanks!

At this moment the latest published version on `ember-dragula` is 1.9.3.
In the master it doesn't depend on bower anymore. It would be great to have a published release with this feature. 

In our project `ember-dragula` is the last bower addicted dependency 😆

**Comment by ro0gr** [comment]
ah.. I see it's blocked by https://github.com/kalcifer/ember-dragula/issues/29

**Comment by oskarrough** [comment]
Thank you! Yes, let's continue there.
