### ISSUE TITLE
Nested components conflict with parent view

### ISSUE THREAD

**Issue by oskarrough** [kalcifer/ember-dragula#4]
Hi, since `ember-dragula-container` relies on `this.get('parentView')` you currently can not have nested components.

Here's an example of what I'd like to achieve:

``` hbs
{{#ember-dragula config=dragulaconfig dragulaEvent='dragulaEvent'}}
    {{#each model.columns as |column|}}
        {{#my-column column=column}}

            {{#each column.row as |row|}}
                {{#ember-dragula-container}}
                    {{my-row row=row}}
                {{/ember-dragula-container}}
            {{/each}}

        {{/my-column}}
    {{/each}}
{{/ember-dragula}}
```

I want to be able to drag the `my-row` component between `my-column` components. How would you do that? One idea would be to pass the `drake` instance from `ember-dragula` to `ember-dragula-container` directly if no parentView is defined.

**Comment by pksjce** [comment]
So, I thought about this. But, I'm not sure how to write the api for passing the drake instance. 
Should I ask the consumer to provide a `setDrake(drake)` to `ember-dragula` and then allow `ember-dragula-container` to take an external `drake` instance?
Do you have any ideas? Of course PRs are welcome.

**Comment by oskarrough** [comment]
I actually did it over the weekend although I got carried away and also updated the code style a bit.

Would you like me to open a PR? Please see the individual commits here https://github.com/kalcifer/ember-dragula/compare/master...oskarrough:master

**Comment by pksjce** [comment]
Merged  with https://github.com/kalcifer/ember-dragula/commit/a4f0894dcef703398d5df998e8feb2f98918c716

**Comment by oskarrough** [comment]
Thank you!
